version: '3'
services:
  app:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
        - home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
volumes:
  home:


